openapi: 3.0.3
info:
  title: trip_vista_api
  version: 1.0.0
  contact: {}
servers:
  - url: http://localhost:5000
    description: Local server
paths:
  /api/v1/auth/login:
    post:
      summary: Login
      description: Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user4@gmail.com
                password:
                  type: number
                  example: 123456
            examples:
              Login:
                value:
                  email: user4@gmail.com
                  password: 123456
      responses:
        '200':
          description: ''
  /api/v1/auth/register:
    post:
      summary: Register user
      description: Register user
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user3@gmail.com
                name:
                  type: string
                  example: hezron
                password:
                  type: number
                  example: 123456
            examples:
              Register user:
                value:
                  email: user3@gmail.com
                  name: hezron
                  password: 123456
      responses:
        '200':
          description: ''
  /api/v1/auth/logout:
    post:
      summary: Logout user
      description: Logout user
      operationId: logoutUser
      responses:
        '200':
          description: ''
  /api/v1/auth/profile:
    get:
      summary: Get User Profile
      description: Get User Profile
      operationId: getUserProfile
      responses:
        '200':
          description: ''
    put:
      summary: Update user
      description: Update user
      operationId: updateUser
      parameters:
        - name: ''
          in: query
          schema:
            type: string
            example: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user3@gmail.com
                name:
                  type: string
                  example: hezron j
                password:
                  type: number
                  example: 123456
            examples:
              Update user:
                value:
                  email: user3@gmail.com
                  name: hezron j
                  password: 123456
      responses:
        '200':
          description: ''
  /api/product/getbill:
    post:
      summary: SEND_MAIL
      description: SEND_MAIL
      operationId: sendMail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                  example: hezronnyamboga6@gmail.com
            examples:
              SEND_MAIL:
                value:
                  userEmail: hezronnyamboga6@gmail.com
      responses:
        '200':
          description: ''
tags: []
